name: 'Scaffoldly Deploy Action'
description: 'Deploy a Scaffoldly Stack Application'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  token:
    description: A GitHub Token
    required: false
    default: ${{ github.token }}
runs:
  using: 'node18'
  main: 'dist/main.js'
  post: 'dist/post.js'
