name: 'Scaffoldly Deploy Action'
description: 'Deploy a Scaffoldly Stack Application'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  region:
    description: 'The AWS Region to deploy to'
    required: false
    default: 'us-east-1'
  role:
    description: 'The AWS Role to use for deployment'
    required: false
    default: ${{ vars.DEPLOYMENT_ROLE }}
runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/post.js'
