name: 'Scaffoldly Deploy Action'
description: 'Deploy a Scaffoldly Stack Application'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  token:
    description: 'The GitHub Token to use for deployment'
    required: false
    default: ${{ github.token }}
  region:
    description: 'The AWS Region to deploy to'
    required: false
    default: 'us-east-1'
  role:
    description: 'The AWS Role to use for deployment'
    required: true
  cli:
    description: 'The CLI to use for deployment'
    required: true
  destroy:
    description: 'If the stack should be destroyed'
    required: false
    default: false
outputs:
  httpApiUri:
    description: 'The URL of the deployed HTTP API'
  stage:
    description: The inferred stage from the branch or PR name
  deployed:
    description: If the stack was deployed.
  destroyed:
    description: If the stack was destroyed.
runs:
  using: 'node20'
  pre: 'dist/pre.js'
  main: 'dist/main.js'
  post: 'dist/post.js'
