name: 'Scaffoldly Deploy Action'
description: 'Deploy a Scaffoldly Stack Application'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  token:
    description: 'The GitHub Token to use for deployment'
    required: false
    default: ${{ github.token }}
  region:
    description: 'The AWS Region to deploy to'
    required: false
    default: 'us-east-1'
  role:
    description: 'The AWS Role to use for deployment'
    required: true
outputs:
  stage:
    description: The inferred stage from the branch or PR name
  deploy:
    description: If the serverless stack should be deployed, defaults to true. False when a pull request is closed.
  destroy:
    description: If the serverless stack should be destroyed, defaults to false. True when a pull request is closed.
runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/post.js'
